update dockerfile

diff --git a/Backend/PetCare/PetCare.Api/Dockerfile b/Backend/PetCare/PetCare.Api/Dockerfile
--- a/Backend/PetCare/PetCare.Api/Dockerfile
+++ b/Backend/PetCare/PetCare.Api/Dockerfile
@@ -25,7 +25,7 @@ RUN dotnet restore "PetCare.Api/PetCare.Api.csproj"
 
 # Копіюємо весь код
 COPY . .
-RUN ls -R /src/PetCare.Infrastructure/Migrations  # Дебаг: перевірка наявності міграцій
+RUN ls -R /src/PetCare.Infrastructure/Migrations || echo "Migrations folder not found"  # Дебаг: перевірка наявності міграцій
 
 # Build всі проєкти
 RUN dotnet build PetCare.Infrastructure/PetCare.Infrastructure.csproj -c Release
@@ -35,7 +35,7 @@ RUN dotnet build PetCare.Api/PetCare.Api.csproj -c Release
 RUN dotnet publish "PetCare.Api/PetCare.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false
 
 # Дебаг: перевірка наявності файлів міграцій у опублікованому результаті
-RUN ls -R /app/publish
+RUN ls -R /app/publish || echo "Publish folder not found"
 
 # ===== Runtime stage =====
 FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
